#define CONTROL 1
#define SYMBOL 2
#define UPPER 4
#define LOWER 8
#define NUMBER 16
#define OPEN (32|SYMBOL)
#define CLOSE (64|SYMBOL)
#define SPACE 128
#define HEXNUM (256|UPPER)
extern int ascii_table[256];